# Generated by Django 2.2.2 on 2019-07-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_follower_count', models.PositiveIntegerField(default=0)),
                ('last_ten_followers', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'FollowerDetail',
                'verbose_name_plural': 'FollowerDetails',
            },
        ),
        migrations.CreateModel(
            name='SearchKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=50)),
                ('consumer_secret', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=50)),
                ('access_token_secret', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.CharField(max_length=30)),
                ('sent', models.BooleanField(default=False)),
                ('tweet', models.CharField(max_length=350)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.SearchKeyWords')),
            ],
        ),
    ]
