# Generated by Django 2.2.2 on 2019-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_follower_count', models.PositiveIntegerField(default=0)),
                ('last_ten_followers', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'FollowerDetail',
                'verbose_name_plural': 'FollowerDetails',
            },
        ),
    ]
