# Generated by Django 2.2.2 on 2019-07-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchkeywords',
            options={'verbose_name': 'SearchKeyWords', 'verbose_name_plural': 'SearchKeyWords'},
        ),
        migrations.AlterModelOptions(
            name='statusurls',
            options={'verbose_name': 'StatusUrls', 'verbose_name_plural': 'StatusUrls'},
        ),
        migrations.AlterModelOptions(
            name='twitterauth',
            options={'verbose_name': 'TwitterAuth', 'verbose_name_plural': 'TwitterAuth'},
        ),
    ]
