# Generated by Django 2.2.2 on 2019-07-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20190702_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusurls',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
