# Generated by Django 2.2.2 on 2019-07-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='screen_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
