# Generated by Django 2.2.2 on 2019-07-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20190702_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusurls',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statusurls',
            name='retweet',
            field=models.BooleanField(default=False),
        ),
    ]
