# Generated by Django 2.2.2 on 2019-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20190703_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusurls',
            name='favorites',
            field=models.BooleanField(default=False, help_text='If this field is green means that you already have marked it as your favorites '),
        ),
        migrations.AlterField(
            model_name='statusurls',
            name='retweet',
            field=models.BooleanField(default=False, help_text='If this field is green means that you already have retweeted '),
        ),
    ]
